### PR TITLE
Create pkg-config files and add missing typedef

### PR DESCRIPTION
**Pull request by raoulh**
This pull request add .pc file generation from the makefile. It also add the missing GLchar typedef in the gl headers.
Both thing are required to build some packages like glmark2 (in openembedded)

### CODE REVIEW

**Comment by raoulh** [comment]
Please can someone review those patches?
Thanks

**Comment by libv** [comment]
On Wed, Mar 05, 2014 at 02:06:54AM -0800, Raoul Hecky wrote:

> Please can someone review those patches?
> Thanks

I will, i have some other things lined up as well. I am just not too 
useful atm, and haven't done anything much in the last month. But don't 
worry, this is and was high in my TODO queue.

Luc Verhaegen.

**Comment by raoulh** [comment]
Ok, great :)
Thanks

**Comment by raoulh** [comment]
Ok... Found the problem. But it's related to openembedded. In fact OE creates debug packages automatically by using:

```
objcopy --only-keep-debug Mali.so
```

And this is failing with the new binary from sunxi-mali-proprietary... Except if I add the -N (means: Do not copy symbol)
I need to find a way of fixing that.

Anyway, the .pc creation is working now, I close this pull-request and will create a new one.

**Pull request closed without merging**
